### ISSUE TITLE
Suggested feature

### ISSUE THREAD

**Issue by GlassDeviant** [JohnsonNicholas/SDVMods#57]
Some sort of tooltip (edit: in the tree mod) for seeds and saplings that tells you what sort of tree (wood or fruit) you are mousing over. Purpose: You have some trees planted and want to plant more, while making sure the types line up, but you can't remember what order you planted them in.

**Comment by JohnsonNicholas** [comment]
You might want to try this: https://www.nexusmods.com/stardewvalley/mods/314?tab=description

**Comment by GlassDeviant** [comment]
Thanks. I have one that does everything except trees, that was my only missing part.

Cheers!
