### ISSUE TITLE
Time Reminder - Alerts for in-game time?

### ISSUE THREAD

**Issue by rmenessec** [JohnsonNicholas/SDVMods#63]
I find it's really easy to get distracted by some task, like adventuring in the mines, and miss an in-game event of some kind, whether it's remembering to trigger a heart event or go fishing for something nocturnal. Would you mind adding the ability to set alerts based on the game clock as well as the system clock?

... Adding optional alerts for events like NPC birthdays would be great, too.

Thanks!

**Comment by JohnsonNicholas** [comment]
I can definitely add that, but I'm not sure how to have it configurable in-game. 

As for birthday reminders, that's a feature already in something like Stardew Notification.  I'll think on it.

**Comment by JohnsonNicholas** [comment]
Added in latest Time Reminder.
