### ISSUE TITLE
Pitch black between 6:00 - 7:20 am during Winter

### ISSUE THREAD

**Issue by gingerbair** [JohnsonNicholas/SDVMods#64]
It seems to just be a weird interaction between this mod and another mod, DeepWoods (id: 2571). The entire screen when outdoors is pitch black during the early morning hours (dusk hours seem to be unaffected), the only exception being the glow from any worn rings. 

here's the log: https://log.smapi.io/j6yadsRr
and here's some screenshots of what it looks like: https://imgur.com/a/31X65fy
my latitude in the config is set to 38.25

**Comment by gingerbair** [comment]
A little update,

(You might already know this, but just in case)

It seems that as the winter season progresses, the length of the pitch blackness seems to lessen. As of the 25th of Winter, the screen's only pitch black for about 10 minutes of in-game time, so until 6:10 am.

**Comment by JohnsonNicholas** [comment]
I've located the issue within DeepWoods. Sadly, because of the nature of the issue, I can't fix it DNT side. I'm discussing it with the author now.

**Comment by gingerbair** [comment]
Cool, thanks for keeping me updated :)

**Comment by JohnsonNicholas** [comment]
DeepWoods has been issued. Closing the event.
